# Create a list of strings
lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']

# Define generator function get_lengths
def get_lengths(input_list):
    """Generator function that yields the
    length of the strings in input_list."""

    # Yield the length of a string
    for person in input_list:
        yield(len(person))

# Print the values generated by get_lengths()
for value in get_lengths(lannister):
    print(value)


'''
O código acima demonstra como criar uma função geradora em Python. Funções geradoras são usadas para produzir uma sequência de valores sob demanda, economizando memória. Neste caso, a função `get_lengths` itera sobre a lista `lannister` e gera o comprimento de cada nome. A saída será: 6, 5, 4, 6, 7. Cada número representa o comprimento dos nomes 'cersei', 'jaime', 'tywin', 'tyrion' e 'joffrey', respectivamente.
'''